# Generated by Django 5.2.17 on 2026-09-25 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nomi")),
                ("params", models.JSONField(default=dict, verbose_name="Parametrlar")),
                (
                    "periodicity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("kunlik", "Har kuni"),
                            ("haftalik", "Har hafta (dushanba)"),
                            ("oylik", "Har oy (1-sana)"),
                            ("choraklik", "Har chorak"),
                            ("yillik", "Har yil"),
                        ],
                        max_length=20,
                        verbose_name="Avtomatik shakllantirish",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Oxirgi shakllantirilgan"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Xabardor qilinadiganlar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hisobot shabloni",
                "verbose_name_plural": "Hisobot shablonlari",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Nomi")),
                ("params", models.JSONField(default=dict, verbose_name="Parametrlar")),
                (
                    "file_xlsx",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Excel fayl"
                    ),
                ),
                (
                    "file_pdf",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="PDF fayl"
                    ),
                ),
                (
                    "is_automatic",
                    models.BooleanField(default=False, verbose_name="Avtomatik"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated",
                        to="reports.reporttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shakllantirilgan hisobot",
                "verbose_name_plural": "Shakllantirilgan hisobotlar",
                "ordering": ["-created_at"],
            },
        ),
    ]
