# Generated by Django 5.2.17 on 2026-09-25 04:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("region", "Hududlar"),
                            ("org_type", "Tashkilot turlari"),
                            ("court_type", "Sud turlari"),
                            ("instance", "Sud instansiyalari (bosqichlari)"),
                            ("case_category", "Ish turkumlari (turlari)"),
                            ("case_status", "Ish holatlari"),
                            ("outcome", "Ish natijalari"),
                            ("document_type", "Hujjat turlari"),
                            ("hearing_result", "Sud majlisi natijalari"),
                            ("deadline_type", "Muddat turlari"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Klassifikator turi",
                    ),
                ),
                ("code", models.SlugField(verbose_name="Kod")),
                ("name", models.CharField(max_length=255, verbose_name="Nomi")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Tartib raqami"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Tizim mantig'ida ishlatiladi: kodi o'zgartirilmaydi, o'chirilmaydi.",
                        verbose_name="Tizim yozuvi",
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=False,
                        help_text="Ish holati uchun: ushbu holatdagi ishlar yakunlangan hisoblanadi.",
                        verbose_name="Yakuniy holat",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Izoh")),
            ],
            options={
                "verbose_name": "Klassifikator qiymati",
                "verbose_name_plural": "Klassifikatorlar",
                "ordering": ["kind", "order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "code"), name="uniq_classifier_kind_code"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Sud nomi")),
                (
                    "address",
                    models.CharField(blank=True, max_length=500, verbose_name="Manzil"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "name_key",
                    models.CharField(db_index=True, editable=False, max_length=500),
                ),
                (
                    "court_type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "court_type"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.classifier",
                        verbose_name="Sud turi",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "region"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.classifier",
                        verbose_name="Hudud",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sud",
                "verbose_name_plural": "Sudlar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=500, verbose_name="To‘liq nomi"),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Qisqartirilgan nomi"
                    ),
                ),
                (
                    "stir",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{9}$", "STIR 9 ta raqamdan iborat bo‘lishi kerak."
                            )
                        ],
                        verbose_name="STIR",
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Tuman (shahar)"
                    ),
                ),
                (
                    "previous_names",
                    models.TextField(
                        blank=True,
                        help_text="Har bir nom alohida qatorda.",
                        verbose_name="Oldingi nomlari",
                    ),
                ),
                (
                    "alt_names",
                    models.TextField(
                        blank=True,
                        help_text="Har bir variant alohida qatorda (kirill, rus tilida va h.k.).",
                        verbose_name="Muqobil yozilish variantlari",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "match_keys",
                    models.TextField(
                        blank=True, editable=False, verbose_name="Qidiruv kalitlari"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "org_type",
                    models.ForeignKey(
                        limit_choices_to={"kind": "org_type"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.classifier",
                        verbose_name="Tashkilot turi",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="core.organization",
                        verbose_name="Yuqori turuvchi tashkilot",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "region"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.classifier",
                        verbose_name="Hudud",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tashkilot",
                "verbose_name_plural": "Tashkilotlar",
                "ordering": ["full_name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("stir", ""), _negated=True),
                        fields=("stir",),
                        name="uniq_organization_stir",
                    )
                ],
            },
        ),
    ]
