# Generated by Django 5.2.17 on 2026-09-25 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nomi")),
                (
                    "adapter",
                    models.CharField(
                        choices=[
                            ("json_api", "Rasmiy API / veb-servis (JSON)"),
                            ("html", "Veb-sahifa jadvalini o‘qish (jadval2.sud.uz)"),
                            ("file", "Fayldan import (JSON / CSV / Excel)"),
                            ("demo", "Sinov (demo) manba"),
                        ],
                        max_length=20,
                        verbose_name="Ulanish usuli",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="Manzil (URL)"
                    ),
                ),
                (
                    "auth_token",
                    models.CharField(
                        blank=True,
                        help_text="API rasmiy kaliti. Sahifada ko‘rsatilmaydi.",
                        max_length=1000,
                        verbose_name="Kirish kaliti (token)",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Maydonlar moslamasi, so‘rov parametrlari, sahifalar ro‘yxati va h.k. (README'ga qarang).",
                        verbose_name="Qo‘shimcha sozlamalar (JSON)",
                    ),
                ),
                (
                    "interval_minutes",
                    models.PositiveIntegerField(
                        default=360, verbose_name="Tekshirish davriyligi (daqiqa)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Oxirgi tekshiruv"
                    ),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Oxirgi muvaffaqiyatli tekshiruv",
                    ),
                ),
                (
                    "last_status",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Oxirgi holat"
                    ),
                ),
            ],
            options={
                "verbose_name": "Integratsiya manbasi",
                "verbose_name_plural": "Integratsiya manbalari",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Boshlangan"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Tugagan"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("jarayonda", "Jarayonda"),
                            ("muvaffaqiyatli", "Muvaffaqiyatli"),
                            ("qisman", "Qisman (xatoliklar bilan)"),
                            ("xato", "Xato"),
                        ],
                        default="jarayonda",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "fetched",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Olingan yozuvlar"
                    ),
                ),
                (
                    "matched",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tizim tashkilotlariga tegishli"
                    ),
                ),
                (
                    "created",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Yangi kartochkalar"
                    ),
                ),
                (
                    "updated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Yangilangan kartochkalar"
                    ),
                ),
                (
                    "unchanged",
                    models.PositiveIntegerField(default=0, verbose_name="O‘zgarmagan"),
                ),
                ("errors", models.TextField(blank=True, verbose_name="Xatoliklar")),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="integration.integrationsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integratsiya seansi",
                "verbose_name_plural": "Integratsiya seanslari",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_key",
                    models.CharField(max_length=500, verbose_name="Tashqi kalit"),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Ma’lumot")),
                ("data_hash", models.CharField(max_length=64)),
                (
                    "first_seen_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Birinchi aniqlangan"
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Oxirgi aniqlangan"
                    ),
                ),
                (
                    "last_changed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Oxirgi o‘zgargan"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_records",
                        to="cases.case",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="integration.integrationsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tashqi yozuv",
                "verbose_name_plural": "Tashqi yozuvlar",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_key"), name="uniq_external_record"
                    )
                ],
            },
        ),
    ]
