# Generated by Django 5.2.17 on 2026-09-25 04:51

import cases.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reg_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="Tizimdagi yagona raqam",
                    ),
                ),
                (
                    "case_number",
                    models.CharField(max_length=100, verbose_name="Sud ishi raqami"),
                ),
                (
                    "case_number_key",
                    models.CharField(db_index=True, editable=False, max_length=100),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("davogar", "Da’vogar"),
                            ("javobgar", "Javobgar"),
                            ("uchinchi", "Uchinchi shaxs"),
                        ],
                        max_length=20,
                        verbose_name="Protsessual maqomi",
                    ),
                ),
                (
                    "other_system_orgs",
                    models.TextField(
                        blank=True,
                        help_text="Integratsiyada aniqlangan qo‘shimcha tashkilotlar.",
                        verbose_name="Ishda ishtirok etuvchi tizimdagi boshqa tashkilotlar",
                    ),
                ),
                ("plaintiffs", models.TextField(blank=True, verbose_name="Da’vogar")),
                ("defendants", models.TextField(blank=True, verbose_name="Javobgar")),
                (
                    "third_parties",
                    models.TextField(blank=True, verbose_name="Uchinchi shaxslar"),
                ),
                ("subject", models.TextField(blank=True, verbose_name="Ish predmeti")),
                (
                    "claim_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Da’vo summasi (so‘m)",
                    ),
                ),
                (
                    "judge",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Mas’ul sudya"
                    ),
                ),
                (
                    "filed_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Da’vo (ariza) berilgan sana",
                    ),
                ),
                (
                    "next_hearing_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Navbatdagi sud majlisi",
                    ),
                ),
                (
                    "outcome_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Yakuniy sud hujjati sanasi"
                    ),
                ),
                (
                    "agency_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("foydasiga", "Agentlik tizimi foydasiga"),
                            ("zarariga", "Agentlik tizimi zarariga"),
                            ("qisman", "Qisman foydasiga"),
                            ("neytral", "Neytral / boshqa"),
                        ],
                        max_length=20,
                        verbose_name="Agentlik tizimi uchun natija",
                    ),
                ),
                (
                    "awarded_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Sud qarori bo‘yicha summa (so‘m)",
                    ),
                ),
                (
                    "outcome_note",
                    models.TextField(blank=True, verbose_name="Natija bo‘yicha izoh"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("integratsiya", "Integratsiya (avtomatik)"),
                            ("qolda", "Foydalanuvchi tomonidan kiritilgan"),
                        ],
                        default="qolda",
                        max_length=20,
                        verbose_name="Ma’lumot manbasi",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Manba nomi"
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="Manbadagi havola"
                    ),
                ),
                (
                    "source_fetched_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Manbadan birinchi olingan vaqt",
                    ),
                ),
                (
                    "source_updated_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Manbadan oxirgi yangilangan vaqt",
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("kiritilmoqda", "Ma’lumot kiritilmoqda"),
                            ("tasdiqlashda", "Yuridik bo‘lim tasdig‘ida"),
                            ("tasdiqlangan", "Tasdiqlangan"),
                            ("qaytarilgan", "Aniqlashtirish uchun qaytarilgan"),
                        ],
                        default="kiritilmoqda",
                        max_length=20,
                        verbose_name="Tasdiqlash holati",
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, verbose_name="Yuridik bo‘lim izohi"),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Bekor qilingan"
                    ),
                ),
                (
                    "cancel_reason",
                    models.TextField(blank=True, verbose_name="Bekor qilish sababi"),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archive_reason",
                    models.TextField(blank=True, verbose_name="Arxivga olish sababi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Ro‘yxatga olingan sana",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Oxirgi yangilangan sana"
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Oxirgi faollik",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "case_category"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.classifier",
                        verbose_name="Ish turkumi (turi)",
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="core.court",
                        verbose_name="Sud",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ro‘yxatga olgan",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "instance"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.classifier",
                        verbose_name="Sud instansiyasi (joriy bosqich)",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="core.organization",
                        verbose_name="Agentlik tizimidagi tashkilot",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "outcome"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.classifier",
                        verbose_name="Ishning yakuniy natijasi",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tashkilotdagi mas’ul xodim",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        limit_choices_to={"kind": "case_status"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.classifier",
                        verbose_name="Ishning joriy holati",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sud ishi",
                "verbose_name_plural": "Sud ishlari",
                "ordering": ["-created_at"],
                "permissions": [
                    ("delete_case_physically", "Sud ishini jismonan o‘chirish")
                ],
            },
        ),
        migrations.CreateModel(
            name="CaseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Hujjat nomi (qisqacha mazmuni)",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Hujjat raqami"
                    ),
                ),
                (
                    "doc_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Hujjat sanasi"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=cases.models.document_upload_to, verbose_name="Fayl"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Asl fayl nomi"
                    ),
                ),
                (
                    "size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Hajmi (bayt)"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Izoh")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yuklangan vaqt"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="cases.case",
                    ),
                ),
                (
                    "doc_type",
                    models.ForeignKey(
                        limit_choices_to={"kind": "document_type"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.classifier",
                        verbose_name="Hujjat turi",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yuklagan foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hujjat",
                "verbose_name_plural": "Hujjatlar",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Vaqt",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("yaratildi", "Kartochka yaratildi"),
                            ("yangilandi", "Ma’lumotlar o‘zgartirildi"),
                            ("holat", "Holat o‘zgartirildi"),
                            ("bosqich", "Sud bosqichi o‘zgartirildi"),
                            ("majlis", "Sud majlisi"),
                            ("muddat", "Nazorat muddati"),
                            ("hujjat", "Hujjat"),
                            ("integratsiya", "Integratsiya orqali yangilandi"),
                            ("tasdiqlash", "Tasdiqlash / qaytarish"),
                            ("biriktirildi", "Biriktirildi"),
                            ("bekor", "Bekor qilindi"),
                            ("arxiv", "Arxivga olindi"),
                            ("tiklandi", "Qayta tiklandi"),
                        ],
                        max_length=20,
                        verbose_name="Hodisa",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=1000, verbose_name="Tavsif"),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="O‘zgarishlar"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Izoh")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="cases.case",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "O‘zgarishlar tarixi yozuvi",
                "verbose_name_plural": "O‘zgarishlar tarixi",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CaseStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Ushbu bosqichdagi ish raqami",
                    ),
                ),
                (
                    "judge",
                    models.CharField(blank=True, max_length=255, verbose_name="Sudya"),
                ),
                (
                    "started_on",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Bosqich boshlangan sana",
                    ),
                ),
                (
                    "ended_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bosqich tugagan sana"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Izoh")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="cases.case",
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.court",
                        verbose_name="Sud",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        limit_choices_to={"kind": "instance"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.classifier",
                        verbose_name="Instansiya",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "outcome"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.classifier",
                        verbose_name="Bosqich natijasi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sud bosqichi",
                "verbose_name_plural": "Sud bosqichlari",
                "ordering": ["started_on", "id"],
            },
        ),
        migrations.CreateModel(
            name="Deadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("protsessual", "Protsessual muddat"),
                            ("ichki", "Ichki nazorat muddati"),
                        ],
                        default="protsessual",
                        max_length=20,
                        verbose_name="Muddat turi",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Mazmuni")),
                ("due_date", models.DateField(db_index=True, verbose_name="Muddat")),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="Bajarildi"),
                ),
                (
                    "done_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bajarilgan vaqt"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Izoh")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deadlines",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deadline_type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "deadline_type"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.classifier",
                        verbose_name="Muddat nomi (klassifikator)",
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deadlines",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mas’ul",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nazorat muddati",
                "verbose_name_plural": "Nazorat muddatlari",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="Hearing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        db_index=True, verbose_name="Sud majlisi sanasi va vaqti"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Joyi (zal)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rejalashtirilgan", "Rejalashtirilgan"),
                            ("otkazildi", "O‘tkazildi"),
                            ("qoldirildi", "Qoldirildi"),
                            ("bekor", "Bekor qilindi"),
                        ],
                        default="rejalashtirilgan",
                        max_length=20,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "result_note",
                    models.TextField(blank=True, verbose_name="Natija bo‘yicha izoh"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("integratsiya", "Integratsiya (avtomatik)"),
                            ("qolda", "Foydalanuvchi tomonidan kiritilgan"),
                        ],
                        default="qolda",
                        max_length=20,
                        verbose_name="Manba",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hearings",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hearings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Majlisda ishtirok etuvchi mas’ul xodim",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "hearing_result"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.classifier",
                        verbose_name="Majlis natijasi",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hearings",
                        to="cases.casestage",
                        verbose_name="Bosqich",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sud majlisi",
                "verbose_name_plural": "Sud majlislari",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_cancelled", False)),
                fields=("case_number_key", "court"),
                name="uniq_active_case_per_court",
            ),
        ),
    ]
