# Generated by Django 5.2.17 on 2026-09-25 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("yangi_ish", "Yangi sud ishi aniqlandi"),
                            ("biriktirildi", "Sud ishi biriktirildi"),
                            (
                                "majlis_belgilandi",
                                "Sud majlisi belgilandi / o‘zgartirildi",
                            ),
                            ("majlis_yaqin", "Sud majlisi yaqinlashmoqda"),
                            ("muddat_yaqin", "Muddat yaqinlashmoqda"),
                            ("muddat_otdi", "Muddat o‘tib ketdi"),
                            ("yangi_malumot", "Yangi ma’lumot yoki hujjat"),
                            ("holat", "Holat yoki bosqich o‘zgardi"),
                            ("yakunlandi", "Ish yakunlandi"),
                            ("qaytarildi", "Aniqlashtirish uchun qaytarildi"),
                            ("tasdiqlash", "Tasdiqlash so‘ralmoqda"),
                            ("yangilanmagan", "Ish uzoq muddat yangilanmagan"),
                            ("tizim", "Tizim xabari"),
                        ],
                        max_length=30,
                        verbose_name="Turi",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Sarlavha")),
                ("message", models.TextField(blank=True, verbose_name="Matn")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Vaqt"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O‘qilgan"
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "emailed",
                    models.BooleanField(
                        default=False, verbose_name="E-pochtaga yuborilgan"
                    ),
                ),
                (
                    "dedup_key",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="cases.case",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Xabarnoma",
                "verbose_name_plural": "Xabarnomalar",
                "ordering": ["-created_at"],
            },
        ),
    ]
